### PR TITLE
GREP1: Add comments on clang-format

### PR DESCRIPTION
**Pull request by mbr0wn**

### CODE REVIEW

**Review by michaelld — COMMENTED** [review]
I think it's appropriate to list the git pre-commit hook you mentioned elsewhere here too ( https://github.com/barisione/clang-format-hooks/ ). Maybe also worth noting that there are probably other such hooks, and list another one that would be conforming to what we want to see for formatting? I'm not familiar with git hooks, so I'm not sure if there are others ... nor how this works behind the scenes ...

**Comment by mbr0wn** [comment]
There's many, they all work differently, and I really don't want to endorse a specific hook implementation in a GREP.

**Comment by michaelld** [comment]
@mbr0wn Makes sense &  NP. That said: For n00b's like me, saying something like `do an internet search for "git pre-commit clang format"` would be useful ... this doesn't indorse any specific hook, whether explicitly or implicitly, yet gives me the information I need to find, understand, and install such a hook.

**Comment by mbr0wn** [comment]
Yeah OK that sounds fine.

**Comment by mbr0wn** [comment]
How do you like this?

**Review by michaelld — APPROVED** [review]
LGTM; thx!

**Comment by noc0lour** [comment]
Maybe you want to add the current version of clang-format the GR codebase depends upon?

**Comment by mbr0wn** [comment]
That's a good idea, how do I find out what that is?

**Pull request merged**
