### PR TITLE
Add GREP2: GNU Radio Versioning

### PR DESCRIPTION
**Pull request by mbr0wn**

### CODE REVIEW

**Comment by mbr0wn** [comment]
FYI @willcode @mormj you can also write directly to the branch for changes you want to make.

**Comment by marcusmueller** [comment]
I'm slightly confused, is this in conflict with the VERSIONING file as included in the source tree?

**Comment by willcode** [comment]
I think they say the same thing from a spec point of view. This one would add more info to help developers understand the impacts of changes, examples of what is allowed for each release type, etc.

**Comment by mbr0wn** [comment]
Yeah what @willcode said. VERSIONING is basically copy & paste from SemVer, but has no list of guarantees. We never define what a "GRC API stability" means, hence this doc.

**Comment by mbr0wn** [comment]
Whoops, fat-fingered.

**Comment by marcusmueller** [comment]
Sounds great!

**Review by mormj — APPROVED** [review]

**Review by mormj — APPROVED** [review]

**Review by dkozel — APPROVED** [review]

**Pull request merged**
